package com.goldwind.mxm.goplus.tool.databasecompare.dao;

import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobNode;
import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobNodeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SesToolDatabaseJobNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int countByExample(SesToolDatabaseJobNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int deleteByExample(SesToolDatabaseJobNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int insert(SesToolDatabaseJobNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int insertSelective(SesToolDatabaseJobNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    List<SesToolDatabaseJobNode> selectByExample(SesToolDatabaseJobNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    SesToolDatabaseJobNode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SesToolDatabaseJobNode record, @Param("example") SesToolDatabaseJobNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SesToolDatabaseJobNode record, @Param("example") SesToolDatabaseJobNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SesToolDatabaseJobNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SesToolDatabaseJobNode record);
}