package com.goldwind.mxm.goplus.tool.databasecompare.dao;

import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseDatasource;
import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseDatasourceExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SesToolDatabaseDatasourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int countByExample(SesToolDatabaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int deleteByExample(SesToolDatabaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int insert(SesToolDatabaseDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int insertSelective(SesToolDatabaseDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    List<SesToolDatabaseDatasource> selectByExample(SesToolDatabaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    SesToolDatabaseDatasource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SesToolDatabaseDatasource record, @Param("example") SesToolDatabaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SesToolDatabaseDatasource record, @Param("example") SesToolDatabaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SesToolDatabaseDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SesToolDatabaseDatasource record);
}