package com.goldwind.mxm.goplus.tool.databasecompare.dao;

import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobPropertyWhere;
import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobPropertyWhereExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SesToolDatabaseJobPropertyWhereMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int countByExample(SesToolDatabaseJobPropertyWhereExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int deleteByExample(SesToolDatabaseJobPropertyWhereExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int insert(SesToolDatabaseJobPropertyWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int insertSelective(SesToolDatabaseJobPropertyWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    List<SesToolDatabaseJobPropertyWhere> selectByExample(SesToolDatabaseJobPropertyWhereExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    SesToolDatabaseJobPropertyWhere selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SesToolDatabaseJobPropertyWhere record, @Param("example") SesToolDatabaseJobPropertyWhereExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SesToolDatabaseJobPropertyWhere record, @Param("example") SesToolDatabaseJobPropertyWhereExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SesToolDatabaseJobPropertyWhere record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property_where
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SesToolDatabaseJobPropertyWhere record);
}