package com.goldwind.mxm.goplus.tool.databasecompare.dao;

import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobPropertyrule;
import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobPropertyruleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SesToolDatabaseJobPropertyruleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int countByExample(SesToolDatabaseJobPropertyruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int deleteByExample(SesToolDatabaseJobPropertyruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int insert(SesToolDatabaseJobPropertyrule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int insertSelective(SesToolDatabaseJobPropertyrule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    List<SesToolDatabaseJobPropertyrule> selectByExample(SesToolDatabaseJobPropertyruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    SesToolDatabaseJobPropertyrule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SesToolDatabaseJobPropertyrule record, @Param("example") SesToolDatabaseJobPropertyruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SesToolDatabaseJobPropertyrule record, @Param("example") SesToolDatabaseJobPropertyruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SesToolDatabaseJobPropertyrule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_propertyrule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SesToolDatabaseJobPropertyrule record);
}