package com.goldwind.mxm.goplus.tool.databasecompare.dao;

import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobVersion;
import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobVersionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SesToolDatabaseJobVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int countByExample(SesToolDatabaseJobVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int deleteByExample(SesToolDatabaseJobVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int insert(SesToolDatabaseJobVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int insertSelective(SesToolDatabaseJobVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    List<SesToolDatabaseJobVersion> selectByExample(SesToolDatabaseJobVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    SesToolDatabaseJobVersion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SesToolDatabaseJobVersion record, @Param("example") SesToolDatabaseJobVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SesToolDatabaseJobVersion record, @Param("example") SesToolDatabaseJobVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SesToolDatabaseJobVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SesToolDatabaseJobVersion record);
}