package com.goldwind.mxm.goplus.tool.databasecompare.dao;

import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobPrimarykey;
import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobPrimarykeyExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SesToolDatabaseJobPrimarykeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int countByExample(SesToolDatabaseJobPrimarykeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int deleteByExample(SesToolDatabaseJobPrimarykeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int insert(SesToolDatabaseJobPrimarykey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int insertSelective(SesToolDatabaseJobPrimarykey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    List<SesToolDatabaseJobPrimarykey> selectByExample(SesToolDatabaseJobPrimarykeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    SesToolDatabaseJobPrimarykey selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SesToolDatabaseJobPrimarykey record, @Param("example") SesToolDatabaseJobPrimarykeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SesToolDatabaseJobPrimarykey record, @Param("example") SesToolDatabaseJobPrimarykeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SesToolDatabaseJobPrimarykey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SesToolDatabaseJobPrimarykey record);
}