package com.goldwind.mxm.goplus.tool.databasecompare.dao;

import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobProperty;
import com.goldwind.mxm.goplus.tool.databasecompare.model.SesToolDatabaseJobPropertyExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SesToolDatabaseJobPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int countByExample(SesToolDatabaseJobPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int deleteByExample(SesToolDatabaseJobPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int insert(SesToolDatabaseJobProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int insertSelective(SesToolDatabaseJobProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    List<SesToolDatabaseJobProperty> selectByExample(SesToolDatabaseJobPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    SesToolDatabaseJobProperty selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SesToolDatabaseJobProperty record, @Param("example") SesToolDatabaseJobPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SesToolDatabaseJobProperty record, @Param("example") SesToolDatabaseJobPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SesToolDatabaseJobProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SesToolDatabaseJobProperty record);
}