package com.goldwind.mxm.goplus.tool.databasecompare.model;

import java.util.Date;

public class SesToolDatabaseJobProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_property.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_property.fk_datasourceid
     *
     * @mbggenerated
     */
    private String fkDatasourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_property.operatedata
     *
     * @mbggenerated
     */
    private Date operatedata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_property.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_property.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_property.dataset
     *
     * @mbggenerated
     */
    private String dataset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_property.pkey
     *
     * @mbggenerated
     */
    private String pkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_property.id
     *
     * @return the value of ses_tool_database_job_property.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_property.id
     *
     * @param id the value for ses_tool_database_job_property.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_property.fk_datasourceid
     *
     * @return the value of ses_tool_database_job_property.fk_datasourceid
     *
     * @mbggenerated
     */
    public String getFkDatasourceid() {
        return fkDatasourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_property.fk_datasourceid
     *
     * @param fkDatasourceid the value for ses_tool_database_job_property.fk_datasourceid
     *
     * @mbggenerated
     */
    public void setFkDatasourceid(String fkDatasourceid) {
        this.fkDatasourceid = fkDatasourceid == null ? null : fkDatasourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_property.operatedata
     *
     * @return the value of ses_tool_database_job_property.operatedata
     *
     * @mbggenerated
     */
    public Date getOperatedata() {
        return operatedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_property.operatedata
     *
     * @param operatedata the value for ses_tool_database_job_property.operatedata
     *
     * @mbggenerated
     */
    public void setOperatedata(Date operatedata) {
        this.operatedata = operatedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_property.createdate
     *
     * @return the value of ses_tool_database_job_property.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_property.createdate
     *
     * @param createdate the value for ses_tool_database_job_property.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_property.state
     *
     * @return the value of ses_tool_database_job_property.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_property.state
     *
     * @param state the value for ses_tool_database_job_property.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_property.dataset
     *
     * @return the value of ses_tool_database_job_property.dataset
     *
     * @mbggenerated
     */
    public String getDataset() {
        return dataset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_property.dataset
     *
     * @param dataset the value for ses_tool_database_job_property.dataset
     *
     * @mbggenerated
     */
    public void setDataset(String dataset) {
        this.dataset = dataset == null ? null : dataset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_property.pkey
     *
     * @return the value of ses_tool_database_job_property.pkey
     *
     * @mbggenerated
     */
    public String getPkey() {
        return pkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_property.pkey
     *
     * @param pkey the value for ses_tool_database_job_property.pkey
     *
     * @mbggenerated
     */
    public void setPkey(String pkey) {
        this.pkey = pkey == null ? null : pkey.trim();
    }
}