package com.goldwind.mxm.goplus.tool.databasecompare.model;

import java.util.Date;

public class SesToolDatabaseJobPrimarykey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_primarykey.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_primarykey.fk_datasourceid
     *
     * @mbggenerated
     */
    private String fkDatasourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_primarykey.looptime
     *
     * @mbggenerated
     */
    private Integer looptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_primarykey.operatedate
     *
     * @mbggenerated
     */
    private Date operatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_primarykey.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_primarykey.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_primarykey.dataset
     *
     * @mbggenerated
     */
    private String dataset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_primarykey.pkey
     *
     * @mbggenerated
     */
    private String pkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_primarykey.id
     *
     * @return the value of ses_tool_database_job_primarykey.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_primarykey.id
     *
     * @param id the value for ses_tool_database_job_primarykey.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_primarykey.fk_datasourceid
     *
     * @return the value of ses_tool_database_job_primarykey.fk_datasourceid
     *
     * @mbggenerated
     */
    public String getFkDatasourceid() {
        return fkDatasourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_primarykey.fk_datasourceid
     *
     * @param fkDatasourceid the value for ses_tool_database_job_primarykey.fk_datasourceid
     *
     * @mbggenerated
     */
    public void setFkDatasourceid(String fkDatasourceid) {
        this.fkDatasourceid = fkDatasourceid == null ? null : fkDatasourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_primarykey.looptime
     *
     * @return the value of ses_tool_database_job_primarykey.looptime
     *
     * @mbggenerated
     */
    public Integer getLooptime() {
        return looptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_primarykey.looptime
     *
     * @param looptime the value for ses_tool_database_job_primarykey.looptime
     *
     * @mbggenerated
     */
    public void setLooptime(Integer looptime) {
        this.looptime = looptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_primarykey.operatedate
     *
     * @return the value of ses_tool_database_job_primarykey.operatedate
     *
     * @mbggenerated
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_primarykey.operatedate
     *
     * @param operatedate the value for ses_tool_database_job_primarykey.operatedate
     *
     * @mbggenerated
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_primarykey.createdate
     *
     * @return the value of ses_tool_database_job_primarykey.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_primarykey.createdate
     *
     * @param createdate the value for ses_tool_database_job_primarykey.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_primarykey.state
     *
     * @return the value of ses_tool_database_job_primarykey.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_primarykey.state
     *
     * @param state the value for ses_tool_database_job_primarykey.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_primarykey.dataset
     *
     * @return the value of ses_tool_database_job_primarykey.dataset
     *
     * @mbggenerated
     */
    public String getDataset() {
        return dataset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_primarykey.dataset
     *
     * @param dataset the value for ses_tool_database_job_primarykey.dataset
     *
     * @mbggenerated
     */
    public void setDataset(String dataset) {
        this.dataset = dataset == null ? null : dataset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_primarykey.pkey
     *
     * @return the value of ses_tool_database_job_primarykey.pkey
     *
     * @mbggenerated
     */
    public String getPkey() {
        return pkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_primarykey.pkey
     *
     * @param pkey the value for ses_tool_database_job_primarykey.pkey
     *
     * @mbggenerated
     */
    public void setPkey(String pkey) {
        this.pkey = pkey == null ? null : pkey.trim();
    }
}