package com.goldwind.mxm.goplus.tool.databasecompare.model;

public class SesToolDatabaseDatasource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_datasource.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_datasource.datasource_name
     *
     * @mbggenerated
     */
    private String datasourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_datasource.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_datasource.datasource_address
     *
     * @mbggenerated
     */
    private String datasourceAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_datasource.datasource_username
     *
     * @mbggenerated
     */
    private String datasourceUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_datasource.datasource_pwd
     *
     * @mbggenerated
     */
    private String datasourcePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_datasource.datasource_dbname
     *
     * @mbggenerated
     */
    private String datasourceDbname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_datasource.id
     *
     * @return the value of ses_tool_database_datasource.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_datasource.id
     *
     * @param id the value for ses_tool_database_datasource.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_datasource.datasource_name
     *
     * @return the value of ses_tool_database_datasource.datasource_name
     *
     * @mbggenerated
     */
    public String getDatasourceName() {
        return datasourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_datasource.datasource_name
     *
     * @param datasourceName the value for ses_tool_database_datasource.datasource_name
     *
     * @mbggenerated
     */
    public void setDatasourceName(String datasourceName) {
        this.datasourceName = datasourceName == null ? null : datasourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_datasource.datasource_type
     *
     * @return the value of ses_tool_database_datasource.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_datasource.datasource_type
     *
     * @param datasourceType the value for ses_tool_database_datasource.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_datasource.datasource_address
     *
     * @return the value of ses_tool_database_datasource.datasource_address
     *
     * @mbggenerated
     */
    public String getDatasourceAddress() {
        return datasourceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_datasource.datasource_address
     *
     * @param datasourceAddress the value for ses_tool_database_datasource.datasource_address
     *
     * @mbggenerated
     */
    public void setDatasourceAddress(String datasourceAddress) {
        this.datasourceAddress = datasourceAddress == null ? null : datasourceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_datasource.datasource_username
     *
     * @return the value of ses_tool_database_datasource.datasource_username
     *
     * @mbggenerated
     */
    public String getDatasourceUsername() {
        return datasourceUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_datasource.datasource_username
     *
     * @param datasourceUsername the value for ses_tool_database_datasource.datasource_username
     *
     * @mbggenerated
     */
    public void setDatasourceUsername(String datasourceUsername) {
        this.datasourceUsername = datasourceUsername == null ? null : datasourceUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_datasource.datasource_pwd
     *
     * @return the value of ses_tool_database_datasource.datasource_pwd
     *
     * @mbggenerated
     */
    public String getDatasourcePwd() {
        return datasourcePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_datasource.datasource_pwd
     *
     * @param datasourcePwd the value for ses_tool_database_datasource.datasource_pwd
     *
     * @mbggenerated
     */
    public void setDatasourcePwd(String datasourcePwd) {
        this.datasourcePwd = datasourcePwd == null ? null : datasourcePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_datasource.datasource_dbname
     *
     * @return the value of ses_tool_database_datasource.datasource_dbname
     *
     * @mbggenerated
     */
    public String getDatasourceDbname() {
        return datasourceDbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_datasource.datasource_dbname
     *
     * @param datasourceDbname the value for ses_tool_database_datasource.datasource_dbname
     *
     * @mbggenerated
     */
    public void setDatasourceDbname(String datasourceDbname) {
        this.datasourceDbname = datasourceDbname == null ? null : datasourceDbname.trim();
    }
}