package com.goldwind.mxm.goplus.tool.databasecompare.model;

import java.util.ArrayList;
import java.util.List;

public class SesToolDatabaseDatasourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public SesToolDatabaseDatasourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameIsNull() {
            addCriterion("datasource_name is null");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameIsNotNull() {
            addCriterion("datasource_name is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameEqualTo(String value) {
            addCriterion("datasource_name =", value, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameNotEqualTo(String value) {
            addCriterion("datasource_name <>", value, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameGreaterThan(String value) {
            addCriterion("datasource_name >", value, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("datasource_name >=", value, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameLessThan(String value) {
            addCriterion("datasource_name <", value, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameLessThanOrEqualTo(String value) {
            addCriterion("datasource_name <=", value, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameLike(String value) {
            addCriterion("datasource_name like", value, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameNotLike(String value) {
            addCriterion("datasource_name not like", value, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameIn(List<String> values) {
            addCriterion("datasource_name in", values, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameNotIn(List<String> values) {
            addCriterion("datasource_name not in", values, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameBetween(String value1, String value2) {
            addCriterion("datasource_name between", value1, value2, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceNameNotBetween(String value1, String value2) {
            addCriterion("datasource_name not between", value1, value2, "datasourceName");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeIsNull() {
            addCriterion("datasource_type is null");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeIsNotNull() {
            addCriterion("datasource_type is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeEqualTo(String value) {
            addCriterion("datasource_type =", value, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeNotEqualTo(String value) {
            addCriterion("datasource_type <>", value, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeGreaterThan(String value) {
            addCriterion("datasource_type >", value, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("datasource_type >=", value, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeLessThan(String value) {
            addCriterion("datasource_type <", value, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeLessThanOrEqualTo(String value) {
            addCriterion("datasource_type <=", value, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeLike(String value) {
            addCriterion("datasource_type like", value, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeNotLike(String value) {
            addCriterion("datasource_type not like", value, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeIn(List<String> values) {
            addCriterion("datasource_type in", values, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeNotIn(List<String> values) {
            addCriterion("datasource_type not in", values, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeBetween(String value1, String value2) {
            addCriterion("datasource_type between", value1, value2, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceTypeNotBetween(String value1, String value2) {
            addCriterion("datasource_type not between", value1, value2, "datasourceType");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressIsNull() {
            addCriterion("datasource_address is null");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressIsNotNull() {
            addCriterion("datasource_address is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressEqualTo(String value) {
            addCriterion("datasource_address =", value, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressNotEqualTo(String value) {
            addCriterion("datasource_address <>", value, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressGreaterThan(String value) {
            addCriterion("datasource_address >", value, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressGreaterThanOrEqualTo(String value) {
            addCriterion("datasource_address >=", value, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressLessThan(String value) {
            addCriterion("datasource_address <", value, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressLessThanOrEqualTo(String value) {
            addCriterion("datasource_address <=", value, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressLike(String value) {
            addCriterion("datasource_address like", value, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressNotLike(String value) {
            addCriterion("datasource_address not like", value, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressIn(List<String> values) {
            addCriterion("datasource_address in", values, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressNotIn(List<String> values) {
            addCriterion("datasource_address not in", values, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressBetween(String value1, String value2) {
            addCriterion("datasource_address between", value1, value2, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceAddressNotBetween(String value1, String value2) {
            addCriterion("datasource_address not between", value1, value2, "datasourceAddress");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameIsNull() {
            addCriterion("datasource_username is null");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameIsNotNull() {
            addCriterion("datasource_username is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameEqualTo(String value) {
            addCriterion("datasource_username =", value, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameNotEqualTo(String value) {
            addCriterion("datasource_username <>", value, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameGreaterThan(String value) {
            addCriterion("datasource_username >", value, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("datasource_username >=", value, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameLessThan(String value) {
            addCriterion("datasource_username <", value, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameLessThanOrEqualTo(String value) {
            addCriterion("datasource_username <=", value, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameLike(String value) {
            addCriterion("datasource_username like", value, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameNotLike(String value) {
            addCriterion("datasource_username not like", value, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameIn(List<String> values) {
            addCriterion("datasource_username in", values, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameNotIn(List<String> values) {
            addCriterion("datasource_username not in", values, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameBetween(String value1, String value2) {
            addCriterion("datasource_username between", value1, value2, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourceUsernameNotBetween(String value1, String value2) {
            addCriterion("datasource_username not between", value1, value2, "datasourceUsername");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdIsNull() {
            addCriterion("datasource_pwd is null");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdIsNotNull() {
            addCriterion("datasource_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdEqualTo(String value) {
            addCriterion("datasource_pwd =", value, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdNotEqualTo(String value) {
            addCriterion("datasource_pwd <>", value, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdGreaterThan(String value) {
            addCriterion("datasource_pwd >", value, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdGreaterThanOrEqualTo(String value) {
            addCriterion("datasource_pwd >=", value, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdLessThan(String value) {
            addCriterion("datasource_pwd <", value, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdLessThanOrEqualTo(String value) {
            addCriterion("datasource_pwd <=", value, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdLike(String value) {
            addCriterion("datasource_pwd like", value, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdNotLike(String value) {
            addCriterion("datasource_pwd not like", value, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdIn(List<String> values) {
            addCriterion("datasource_pwd in", values, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdNotIn(List<String> values) {
            addCriterion("datasource_pwd not in", values, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdBetween(String value1, String value2) {
            addCriterion("datasource_pwd between", value1, value2, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourcePwdNotBetween(String value1, String value2) {
            addCriterion("datasource_pwd not between", value1, value2, "datasourcePwd");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameIsNull() {
            addCriterion("datasource_dbname is null");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameIsNotNull() {
            addCriterion("datasource_dbname is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameEqualTo(String value) {
            addCriterion("datasource_dbname =", value, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameNotEqualTo(String value) {
            addCriterion("datasource_dbname <>", value, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameGreaterThan(String value) {
            addCriterion("datasource_dbname >", value, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameGreaterThanOrEqualTo(String value) {
            addCriterion("datasource_dbname >=", value, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameLessThan(String value) {
            addCriterion("datasource_dbname <", value, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameLessThanOrEqualTo(String value) {
            addCriterion("datasource_dbname <=", value, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameLike(String value) {
            addCriterion("datasource_dbname like", value, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameNotLike(String value) {
            addCriterion("datasource_dbname not like", value, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameIn(List<String> values) {
            addCriterion("datasource_dbname in", values, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameNotIn(List<String> values) {
            addCriterion("datasource_dbname not in", values, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameBetween(String value1, String value2) {
            addCriterion("datasource_dbname between", value1, value2, "datasourceDbname");
            return (Criteria) this;
        }

        public Criteria andDatasourceDbnameNotBetween(String value1, String value2) {
            addCriterion("datasource_dbname not between", value1, value2, "datasourceDbname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ses_tool_database_datasource
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}