package com.goldwind.mxm.goplus.tool.databasecompare.model;

public class SesToolDatabaseJobNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.fk_job_id
     *
     * @mbggenerated
     */
    private String fkJobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.node_name
     *
     * @mbggenerated
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.node_type
     *
     * @mbggenerated
     */
    private Integer nodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.dataset
     *
     * @mbggenerated
     */
    private String dataset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.pkey
     *
     * @mbggenerated
     */
    private String pkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.ishave
     *
     * @mbggenerated
     */
    private Integer ishave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.node_index
     *
     * @mbggenerated
     */
    private Integer nodeIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.expirydate
     *
     * @mbggenerated
     */
    private Integer expirydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.record_count
     *
     * @mbggenerated
     */
    private Integer recordCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_node.compare
     *
     * @mbggenerated
     */
    private String compare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.id
     *
     * @return the value of ses_tool_database_job_node.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.id
     *
     * @param id the value for ses_tool_database_job_node.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.fk_job_id
     *
     * @return the value of ses_tool_database_job_node.fk_job_id
     *
     * @mbggenerated
     */
    public String getFkJobId() {
        return fkJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.fk_job_id
     *
     * @param fkJobId the value for ses_tool_database_job_node.fk_job_id
     *
     * @mbggenerated
     */
    public void setFkJobId(String fkJobId) {
        this.fkJobId = fkJobId == null ? null : fkJobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.node_name
     *
     * @return the value of ses_tool_database_job_node.node_name
     *
     * @mbggenerated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.node_name
     *
     * @param nodeName the value for ses_tool_database_job_node.node_name
     *
     * @mbggenerated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.node_type
     *
     * @return the value of ses_tool_database_job_node.node_type
     *
     * @mbggenerated
     */
    public Integer getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.node_type
     *
     * @param nodeType the value for ses_tool_database_job_node.node_type
     *
     * @mbggenerated
     */
    public void setNodeType(Integer nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.dataset
     *
     * @return the value of ses_tool_database_job_node.dataset
     *
     * @mbggenerated
     */
    public String getDataset() {
        return dataset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.dataset
     *
     * @param dataset the value for ses_tool_database_job_node.dataset
     *
     * @mbggenerated
     */
    public void setDataset(String dataset) {
        this.dataset = dataset == null ? null : dataset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.pkey
     *
     * @return the value of ses_tool_database_job_node.pkey
     *
     * @mbggenerated
     */
    public String getPkey() {
        return pkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.pkey
     *
     * @param pkey the value for ses_tool_database_job_node.pkey
     *
     * @mbggenerated
     */
    public void setPkey(String pkey) {
        this.pkey = pkey == null ? null : pkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.ishave
     *
     * @return the value of ses_tool_database_job_node.ishave
     *
     * @mbggenerated
     */
    public Integer getIshave() {
        return ishave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.ishave
     *
     * @param ishave the value for ses_tool_database_job_node.ishave
     *
     * @mbggenerated
     */
    public void setIshave(Integer ishave) {
        this.ishave = ishave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.node_index
     *
     * @return the value of ses_tool_database_job_node.node_index
     *
     * @mbggenerated
     */
    public Integer getNodeIndex() {
        return nodeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.node_index
     *
     * @param nodeIndex the value for ses_tool_database_job_node.node_index
     *
     * @mbggenerated
     */
    public void setNodeIndex(Integer nodeIndex) {
        this.nodeIndex = nodeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.expirydate
     *
     * @return the value of ses_tool_database_job_node.expirydate
     *
     * @mbggenerated
     */
    public Integer getExpirydate() {
        return expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.expirydate
     *
     * @param expirydate the value for ses_tool_database_job_node.expirydate
     *
     * @mbggenerated
     */
    public void setExpirydate(Integer expirydate) {
        this.expirydate = expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.record_count
     *
     * @return the value of ses_tool_database_job_node.record_count
     *
     * @mbggenerated
     */
    public Integer getRecordCount() {
        return recordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.record_count
     *
     * @param recordCount the value for ses_tool_database_job_node.record_count
     *
     * @mbggenerated
     */
    public void setRecordCount(Integer recordCount) {
        this.recordCount = recordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_node.compare
     *
     * @return the value of ses_tool_database_job_node.compare
     *
     * @mbggenerated
     */
    public String getCompare() {
        return compare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_node.compare
     *
     * @param compare the value for ses_tool_database_job_node.compare
     *
     * @mbggenerated
     */
    public void setCompare(String compare) {
        this.compare = compare == null ? null : compare.trim();
    }
}