package com.goldwind.mxm.goplus.tool.databasecompare.model;

public class SesToolDatabaseJobPropertyrule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_propertyrule.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_propertyrule.property_name
     *
     * @mbggenerated
     */
    private String propertyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_propertyrule.isnull
     *
     * @mbggenerated
     */
    private Integer isnull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_propertyrule.max
     *
     * @mbggenerated
     */
    private Double max;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_propertyrule.min
     *
     * @mbggenerated
     */
    private Double min;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_propertyrule.property_type
     *
     * @mbggenerated
     */
    private String propertyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_propertyrule.fk_job_id
     *
     * @mbggenerated
     */
    private String fkJobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_propertyrule.equal
     *
     * @mbggenerated
     */
    private String equal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_propertyrule.id
     *
     * @return the value of ses_tool_database_job_propertyrule.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_propertyrule.id
     *
     * @param id the value for ses_tool_database_job_propertyrule.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_propertyrule.property_name
     *
     * @return the value of ses_tool_database_job_propertyrule.property_name
     *
     * @mbggenerated
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_propertyrule.property_name
     *
     * @param propertyName the value for ses_tool_database_job_propertyrule.property_name
     *
     * @mbggenerated
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_propertyrule.isnull
     *
     * @return the value of ses_tool_database_job_propertyrule.isnull
     *
     * @mbggenerated
     */
    public Integer getIsnull() {
        return isnull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_propertyrule.isnull
     *
     * @param isnull the value for ses_tool_database_job_propertyrule.isnull
     *
     * @mbggenerated
     */
    public void setIsnull(Integer isnull) {
        this.isnull = isnull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_propertyrule.max
     *
     * @return the value of ses_tool_database_job_propertyrule.max
     *
     * @mbggenerated
     */
    public Double getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_propertyrule.max
     *
     * @param max the value for ses_tool_database_job_propertyrule.max
     *
     * @mbggenerated
     */
    public void setMax(Double max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_propertyrule.min
     *
     * @return the value of ses_tool_database_job_propertyrule.min
     *
     * @mbggenerated
     */
    public Double getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_propertyrule.min
     *
     * @param min the value for ses_tool_database_job_propertyrule.min
     *
     * @mbggenerated
     */
    public void setMin(Double min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_propertyrule.property_type
     *
     * @return the value of ses_tool_database_job_propertyrule.property_type
     *
     * @mbggenerated
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_propertyrule.property_type
     *
     * @param propertyType the value for ses_tool_database_job_propertyrule.property_type
     *
     * @mbggenerated
     */
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType == null ? null : propertyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_propertyrule.fk_job_id
     *
     * @return the value of ses_tool_database_job_propertyrule.fk_job_id
     *
     * @mbggenerated
     */
    public String getFkJobId() {
        return fkJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_propertyrule.fk_job_id
     *
     * @param fkJobId the value for ses_tool_database_job_propertyrule.fk_job_id
     *
     * @mbggenerated
     */
    public void setFkJobId(String fkJobId) {
        this.fkJobId = fkJobId == null ? null : fkJobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_propertyrule.equal
     *
     * @return the value of ses_tool_database_job_propertyrule.equal
     *
     * @mbggenerated
     */
    public String getEqual() {
        return equal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_propertyrule.equal
     *
     * @param equal the value for ses_tool_database_job_propertyrule.equal
     *
     * @mbggenerated
     */
    public void setEqual(String equal) {
        this.equal = equal == null ? null : equal.trim();
    }
}