package com.goldwind.mxm.goplus.tool.databasecompare.model;

public class SesToolDatabaseSourceLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_source_log.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_source_log.fk_datasourceid
     *
     * @mbggenerated
     */
    private String fkDatasourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_source_log.fk_job_id
     *
     * @mbggenerated
     */
    private String fkJobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_source_log.fk_job_node_id
     *
     * @mbggenerated
     */
    private String fkJobNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_source_log.log_result
     *
     * @mbggenerated
     */
    private String logResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_source_log.fk_version_id
     *
     * @mbggenerated
     */
    private String fkVersionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_source_log.id
     *
     * @return the value of ses_tool_database_source_log.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_source_log.id
     *
     * @param id the value for ses_tool_database_source_log.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_source_log.fk_datasourceid
     *
     * @return the value of ses_tool_database_source_log.fk_datasourceid
     *
     * @mbggenerated
     */
    public String getFkDatasourceid() {
        return fkDatasourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_source_log.fk_datasourceid
     *
     * @param fkDatasourceid the value for ses_tool_database_source_log.fk_datasourceid
     *
     * @mbggenerated
     */
    public void setFkDatasourceid(String fkDatasourceid) {
        this.fkDatasourceid = fkDatasourceid == null ? null : fkDatasourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_source_log.fk_job_id
     *
     * @return the value of ses_tool_database_source_log.fk_job_id
     *
     * @mbggenerated
     */
    public String getFkJobId() {
        return fkJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_source_log.fk_job_id
     *
     * @param fkJobId the value for ses_tool_database_source_log.fk_job_id
     *
     * @mbggenerated
     */
    public void setFkJobId(String fkJobId) {
        this.fkJobId = fkJobId == null ? null : fkJobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_source_log.fk_job_node_id
     *
     * @return the value of ses_tool_database_source_log.fk_job_node_id
     *
     * @mbggenerated
     */
    public String getFkJobNodeId() {
        return fkJobNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_source_log.fk_job_node_id
     *
     * @param fkJobNodeId the value for ses_tool_database_source_log.fk_job_node_id
     *
     * @mbggenerated
     */
    public void setFkJobNodeId(String fkJobNodeId) {
        this.fkJobNodeId = fkJobNodeId == null ? null : fkJobNodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_source_log.log_result
     *
     * @return the value of ses_tool_database_source_log.log_result
     *
     * @mbggenerated
     */
    public String getLogResult() {
        return logResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_source_log.log_result
     *
     * @param logResult the value for ses_tool_database_source_log.log_result
     *
     * @mbggenerated
     */
    public void setLogResult(String logResult) {
        this.logResult = logResult == null ? null : logResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_source_log.fk_version_id
     *
     * @return the value of ses_tool_database_source_log.fk_version_id
     *
     * @mbggenerated
     */
    public String getFkVersionId() {
        return fkVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_source_log.fk_version_id
     *
     * @param fkVersionId the value for ses_tool_database_source_log.fk_version_id
     *
     * @mbggenerated
     */
    public void setFkVersionId(String fkVersionId) {
        this.fkVersionId = fkVersionId == null ? null : fkVersionId.trim();
    }
}