package com.goldwind.mxm.goplus.tool.databasecompare.model;

import java.util.Date;

public class SesToolDatabaseJobVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_version.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_version.fk_job_id
     *
     * @mbggenerated
     */
    private String fkJobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_version.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_version.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_version.endtime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_version.version_type
     *
     * @mbggenerated
     */
    private String versionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_version.lastflag
     *
     * @mbggenerated
     */
    private Integer lastflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ses_tool_database_job_version.t_flag
     *
     * @mbggenerated
     */
    private Long tFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_version.id
     *
     * @return the value of ses_tool_database_job_version.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_version.id
     *
     * @param id the value for ses_tool_database_job_version.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_version.fk_job_id
     *
     * @return the value of ses_tool_database_job_version.fk_job_id
     *
     * @mbggenerated
     */
    public String getFkJobId() {
        return fkJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_version.fk_job_id
     *
     * @param fkJobId the value for ses_tool_database_job_version.fk_job_id
     *
     * @mbggenerated
     */
    public void setFkJobId(String fkJobId) {
        this.fkJobId = fkJobId == null ? null : fkJobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_version.version
     *
     * @return the value of ses_tool_database_job_version.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_version.version
     *
     * @param version the value for ses_tool_database_job_version.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_version.createtime
     *
     * @return the value of ses_tool_database_job_version.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_version.createtime
     *
     * @param createtime the value for ses_tool_database_job_version.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_version.endtime
     *
     * @return the value of ses_tool_database_job_version.endtime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_version.endtime
     *
     * @param endtime the value for ses_tool_database_job_version.endtime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_version.version_type
     *
     * @return the value of ses_tool_database_job_version.version_type
     *
     * @mbggenerated
     */
    public String getVersionType() {
        return versionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_version.version_type
     *
     * @param versionType the value for ses_tool_database_job_version.version_type
     *
     * @mbggenerated
     */
    public void setVersionType(String versionType) {
        this.versionType = versionType == null ? null : versionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_version.lastflag
     *
     * @return the value of ses_tool_database_job_version.lastflag
     *
     * @mbggenerated
     */
    public Integer getLastflag() {
        return lastflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_version.lastflag
     *
     * @param lastflag the value for ses_tool_database_job_version.lastflag
     *
     * @mbggenerated
     */
    public void setLastflag(Integer lastflag) {
        this.lastflag = lastflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ses_tool_database_job_version.t_flag
     *
     * @return the value of ses_tool_database_job_version.t_flag
     *
     * @mbggenerated
     */
    public Long gettFlag() {
        return tFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ses_tool_database_job_version.t_flag
     *
     * @param tFlag the value for ses_tool_database_job_version.t_flag
     *
     * @mbggenerated
     */
    public void settFlag(Long tFlag) {
        this.tFlag = tFlag;
    }
}