package com.goldwind.mxm.goplus.tool.databasecompare.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SesToolDatabaseJobPrimarykeyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public SesToolDatabaseJobPrimarykeyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidIsNull() {
            addCriterion("fk_datasourceid is null");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidIsNotNull() {
            addCriterion("fk_datasourceid is not null");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidEqualTo(String value) {
            addCriterion("fk_datasourceid =", value, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidNotEqualTo(String value) {
            addCriterion("fk_datasourceid <>", value, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidGreaterThan(String value) {
            addCriterion("fk_datasourceid >", value, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidGreaterThanOrEqualTo(String value) {
            addCriterion("fk_datasourceid >=", value, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidLessThan(String value) {
            addCriterion("fk_datasourceid <", value, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidLessThanOrEqualTo(String value) {
            addCriterion("fk_datasourceid <=", value, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidLike(String value) {
            addCriterion("fk_datasourceid like", value, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidNotLike(String value) {
            addCriterion("fk_datasourceid not like", value, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidIn(List<String> values) {
            addCriterion("fk_datasourceid in", values, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidNotIn(List<String> values) {
            addCriterion("fk_datasourceid not in", values, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidBetween(String value1, String value2) {
            addCriterion("fk_datasourceid between", value1, value2, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andFkDatasourceidNotBetween(String value1, String value2) {
            addCriterion("fk_datasourceid not between", value1, value2, "fkDatasourceid");
            return (Criteria) this;
        }

        public Criteria andLooptimeIsNull() {
            addCriterion("looptime is null");
            return (Criteria) this;
        }

        public Criteria andLooptimeIsNotNull() {
            addCriterion("looptime is not null");
            return (Criteria) this;
        }

        public Criteria andLooptimeEqualTo(Integer value) {
            addCriterion("looptime =", value, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeNotEqualTo(Integer value) {
            addCriterion("looptime <>", value, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeGreaterThan(Integer value) {
            addCriterion("looptime >", value, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("looptime >=", value, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeLessThan(Integer value) {
            addCriterion("looptime <", value, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeLessThanOrEqualTo(Integer value) {
            addCriterion("looptime <=", value, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeIn(List<Integer> values) {
            addCriterion("looptime in", values, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeNotIn(List<Integer> values) {
            addCriterion("looptime not in", values, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeBetween(Integer value1, Integer value2) {
            addCriterion("looptime between", value1, value2, "looptime");
            return (Criteria) this;
        }

        public Criteria andLooptimeNotBetween(Integer value1, Integer value2) {
            addCriterion("looptime not between", value1, value2, "looptime");
            return (Criteria) this;
        }

        public Criteria andOperatedateIsNull() {
            addCriterion("operatedate is null");
            return (Criteria) this;
        }

        public Criteria andOperatedateIsNotNull() {
            addCriterion("operatedate is not null");
            return (Criteria) this;
        }

        public Criteria andOperatedateEqualTo(Date value) {
            addCriterion("operatedate =", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotEqualTo(Date value) {
            addCriterion("operatedate <>", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateGreaterThan(Date value) {
            addCriterion("operatedate >", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("operatedate >=", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateLessThan(Date value) {
            addCriterion("operatedate <", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateLessThanOrEqualTo(Date value) {
            addCriterion("operatedate <=", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateIn(List<Date> values) {
            addCriterion("operatedate in", values, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotIn(List<Date> values) {
            addCriterion("operatedate not in", values, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateBetween(Date value1, Date value2) {
            addCriterion("operatedate between", value1, value2, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotBetween(Date value1, Date value2) {
            addCriterion("operatedate not between", value1, value2, "operatedate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDatasetIsNull() {
            addCriterion("dataset is null");
            return (Criteria) this;
        }

        public Criteria andDatasetIsNotNull() {
            addCriterion("dataset is not null");
            return (Criteria) this;
        }

        public Criteria andDatasetEqualTo(String value) {
            addCriterion("dataset =", value, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetNotEqualTo(String value) {
            addCriterion("dataset <>", value, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetGreaterThan(String value) {
            addCriterion("dataset >", value, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetGreaterThanOrEqualTo(String value) {
            addCriterion("dataset >=", value, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetLessThan(String value) {
            addCriterion("dataset <", value, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetLessThanOrEqualTo(String value) {
            addCriterion("dataset <=", value, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetLike(String value) {
            addCriterion("dataset like", value, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetNotLike(String value) {
            addCriterion("dataset not like", value, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetIn(List<String> values) {
            addCriterion("dataset in", values, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetNotIn(List<String> values) {
            addCriterion("dataset not in", values, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetBetween(String value1, String value2) {
            addCriterion("dataset between", value1, value2, "dataset");
            return (Criteria) this;
        }

        public Criteria andDatasetNotBetween(String value1, String value2) {
            addCriterion("dataset not between", value1, value2, "dataset");
            return (Criteria) this;
        }

        public Criteria andPkeyIsNull() {
            addCriterion("pkey is null");
            return (Criteria) this;
        }

        public Criteria andPkeyIsNotNull() {
            addCriterion("pkey is not null");
            return (Criteria) this;
        }

        public Criteria andPkeyEqualTo(String value) {
            addCriterion("pkey =", value, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyNotEqualTo(String value) {
            addCriterion("pkey <>", value, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyGreaterThan(String value) {
            addCriterion("pkey >", value, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyGreaterThanOrEqualTo(String value) {
            addCriterion("pkey >=", value, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyLessThan(String value) {
            addCriterion("pkey <", value, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyLessThanOrEqualTo(String value) {
            addCriterion("pkey <=", value, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyLike(String value) {
            addCriterion("pkey like", value, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyNotLike(String value) {
            addCriterion("pkey not like", value, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyIn(List<String> values) {
            addCriterion("pkey in", values, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyNotIn(List<String> values) {
            addCriterion("pkey not in", values, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyBetween(String value1, String value2) {
            addCriterion("pkey between", value1, value2, "pkey");
            return (Criteria) this;
        }

        public Criteria andPkeyNotBetween(String value1, String value2) {
            addCriterion("pkey not between", value1, value2, "pkey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ses_tool_database_job_primarykey
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}